spring:
  kafka:
    kafka-server: localhost:9092
    consumer:
      # groupid는 컨슈머 그룹을 식별하는 id로서, 동일한 그룹id를 가진 컴슈머들은 메시지를 분담해서 consume
      # 만약 여러 컨슈머가 다른 group-id를 가지고 현 topic을 리슨하면 각기 메시지를 수신하여 메시지 전파 효과 발생
      group-id: product-group
      # kafka내에 들어와있는 메시지중에 처음들어와있는 메시지부터 읽기시작(latest: 현시점이후로 들어오는 메시지만 read)
      # 현 프로젝트에서는 Ordering(publish, 게시자)이고, Product(subscribe, 구독자)이며, kafka(브로커)라고 볼수있다
      # 이런 상황에서 만약 product서버가 죽는 다면, 다시 product서버가 살아라면
      # earliest: kafka있는 메시지를 처음부터 읽는 것이고, latest: product 서버가 살아난 이후부터 읽는다.
      auto-offset-reset: earliest